const route=require('express').Router()
const{login,getStudent,getStudentbyid,deleteStudent,updateStudent,addStudent}=require('../controllers/crudcontroller')
const{verifyToken}=require('../middleware/authMiddleware')
route.post('/login',login)
route.post("/addStudent",addStudent)
route.get("/getStudents",verifyToken,getStudent)
route.get("/getStudent/:studentId",getStudentbyid)
route.put("/student/:id",updateStudent)
route.delete("/deleteStudent",deleteStudent)
module.exports=route