const route=require('express').Router()
const{login,getStudent,getStudentbyid,deleteStudent,updateStudent,register,uploadFiles}=require('../controllers/crudcontroller')
const{verifyToken}=require('../middleware/authMiddleware')
const {upload}=require('../files/files')
route.post('/login',login)
route.post("/register",register)
route.get("/getDetails",verifyToken,getStudent)
route.get("/getDetail/:studentId",getStudentbyid)
route.put("/updateDetails/:id",updateStudent)
route.delete("/deleteDetails/:id",deleteStudent)
route.post("/uploadFiles",uploadFiles)
module.exports=route