const route=require('express').Router()
const{login,getStudent,getStudentbyid,deleteStudent,updateStudent,register}=require('../controllers/crudcontroller')
const{verifyToken}=require('../middleware/authMiddleware')
route.post('/login',login)
route.post("/register",register)
route.get("/getDetails",verifyToken,getStudent)
route.get("/getDetail/:studentId",getStudentbyid)
route.put("/updateDetails/:id",updateStudent)
route.delete("/deleteDetails",deleteStudent)
module.exports=route