const express=require('express')
const fs=require('fs')
const url=require('url')
const mongoose=require('mongoose')
const Tarushi=require('./models/userModel')
const app=express()
const cors=require('cors')
app.use(express.json())
const {verifyToken}=require('./middleware/authMiddleware')
const route=require('./routes/userRoutes')
const routes=require('./routes/projectRoute')
app.use(express.json())
app.use(cors())

mongoose.connect('mongodb://localhost:27017')
.then(()=>console.log("DB connected"))
.catch((err)=>console.log(err))

app.use("/api",route)
app.use("/api",routes)
app.listen(5000,()=>{
    console.log("Server started")
})