const os=require('os')

console.log(os.cpus())
console.log(os.arch())
console.log(os.platform())
console.log(os.hostname())
console.log(os.totalmem())
console.log(os.freemem())
console.log(os.homedir())
console.log(os.getPriority())
console.log(os.tmpdir())
console.log(os.availableParallelism())
console.log(os.machine())
console.log(os.loadavg())
console.log(os.networkInterfaces())
console.log(os.tmpdir())
console.log(os.userInfo())
console.log(os.uptime())